base: ghcr.io/taukakao/desktop:firstsetup-flathub
name: Vanilla Desktop Tests
id: vanilla-desktop-tests
labels:
  maintainer: Tau
args:
  DEBIAN_FRONTEND: noninteractive

modules:
- name: install console-data
  type: shell
  commands:
  - apt install console-data
  - ls /usr/share/kbd/keymaps/

modules:
- name: initialize
  type: shell
  commands:
  - lpkg --unlock

- name: switch vconsole.conf
  type: shell
  commands:
  - mv /etc/vconsole.conf /etc/vconsole.conf.old
  - mv /etc/vconsole.conf.new /etc/vconsole.conf
  - sed -i 's/KEYMAP=n/KEYMAP=y/' /etc/initramfs-tools/initramfs.conf
  
- name: cleanup
  type: shell
  commands:
  - apt autoremove -y
  - apt clean
  - lpkg --lock
