base: ghcr.io/vanilla-os/desktop:main
name: Vanilla Desktop Tests
id: vanilla-desktop-tests
labels:
  maintainer: Tau
args:
  DEBIAN_FRONTEND: noninteractive

modules:
- name: initialize
  type: shell
  commands:
  - lpkg --unlock

- name: switch vconsole.conf
  type: shell
  commands:
  - mv /etc/vconsole.conf /etc/vconsole.conf.old
  - mv /etc/vconsole.conf.new /etc/vconsole.conf
  
- name: cleanup
  type: shell
  commands:
  - apt autoremove -y
  - apt clean
  - lpkg --lock
