base: ghcr.io/vanilla-os/desktop:main
name: Vanilla Desktop Tests
id: vanilla-desktop-tests
labels:
  maintainer: Tau
args:
  DEBIAN_FRONTEND: noninteractive

modules:
- name: initialize
  type: shell
  commands:
  - lpkg --unlock

- name: use os-prober
  type: shell
  commands:
  - sed -i 's/#GRUB_DISABLE_OS_PROBER/GRUB_DISABLE_OS_PROBER/' /etc/default/grub
  
- name: cleanup
  type: shell
  commands:
  - apt autoremove -y
  - apt clean
  - lpkg --lock
